UMS_2/UserManagementSystem/Controllers/ExistingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UserManagementSystem.Controllers
{
    public class ExistingController : Controller
    {
        public ActionResult Exist()
        {
            return View();
        }
        public ActionResult Email()
        {
            String email = Request["email"];
            bool flag1 = UMS.BAL.UserBO.validateEmail(email);
            if (flag1)
            {
                TempData["email"] = email;
                String subject = "Reset Password Code";
                Random rnd = new Random();
                int num = rnd.Next(12000, 90000);
                Session["Code"] = num.ToString();
                String body = num.ToString();
                bool flag = UMS.BAL.UserBO.Email(email, subject, body);
                return View();
            }
            else
            {
                Response.Write("<script> alert('Wrong Email');</script>");
                return View("Exist");
            }
            
        }
        public ActionResult UpdatePassword()
        {
            String code = Request["code"];
            String temp = (String)Session["code"];
            if (code == temp)
                return View();
            else
            {
                Response.Write("<script> alert('Wrong Code');</script>");
                return View("Email");
            }
                
        }
        public ActionResult login()
        {
            String login = Request["login"];
            String pwd = Request["password"];
            bool flag = UMS.BAL.UserBO.login(login,pwd);
            if (!flag)
            {
                Response.Write("<script> alert('Wrong username or password');</script>");
            }
            else
            {
                TempData["login"] = login;
                return RedirectToAction("Home", "User", null); ;
            }
            return View("Exist");
        }
        public ActionResult ResetPassword()
        {
            String pwd = Request["code"];
            String email = (String)TempData["email"];
            String login = UMS.BAL.UserBO.resetPassword(email, pwd);
            TempData["login"] = login;
            return RedirectToAction("Home", "User", null);
        }
    }
}

UMS_2/UserManagementSystem/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using UMS.DAL;
using UMS.Entities;

namespace UserManagementSystem.Controllers
{
    public class UserController : Controller
    {
        public ActionResult start()
        {
            return View();
        }
        public ActionResult logout()
        {
            return View("start");
        }
        [HttpPost]
        public ActionResult Save()
        { 
            UserDTO dto = new UserDTO();
            var name = "";
            if (Request.Files["image"] != null)
            {
                var file = Request.Files["image"];
                if (file.FileName != "")
                {
                    var ext = System.IO.Path.GetExtension(file.FileName);
                    name = Guid.NewGuid().ToString() + ext;
                    var rootPath = Server.MapPath("~/UploadedFiles");
                    var fileSavePath = System.IO.Path.Combine(rootPath, name);
                    file.SaveAs(fileSavePath);
                    
                }
            }
            if (name == "")
                dto.ImageName = (String)Session["image"];
            else
                dto.ImageName = name;
            dto.UserID = (Int32)Session["UserID"];
            dto.Name = Request["Name"];
            dto.login = Request["login"];
            dto.password = Request["password"];
            String str = Request["gender"];
            if (Request["gender"] == "male")
                dto.gender = 'M';
            else
                dto.gender = 'F';
            dto.address = Request["address"];
            dto.age = Convert.ToInt32(Request["age"]);
            dto.NIC = Request["NIC"];
            dto.DOB = Convert.ToDateTime(Request["DOB"]);
            if (Request["isCricket"] != null)
                dto.isCricket = true;
            else
                dto.isCricket = false;
            if (Request["Hockey"] != null)
                dto.Hockey = true;
            else
                dto.Hockey = false;
            if (Request["Chess"] != null)
                dto.Chess = true;
            else
                dto.Chess = false;

            dto.CreatedOn = DateTime.Now;
            dto.Email = Request["Email"];
            int count = UMS.BAL.UserBO.Save(dto);
            if (count == -1)
                Response.Write("<script> alert('User already Exist');</script>");
            else if (count > 0)
                Response.Write("<script> alert('Data Inserted Sucessfully');</script>");
            else if (count == -2)
                Response.Write("<script> alert('Data Updated Sucessfully');</script>");
            else
                Response.Write("<script> alert('Data Updated Sucessfully');</script>");
            if (count != -1)
                return View(dto);
            else
                return View("New", dto);
        }

        public ActionResult New()
        {
            UserDTO dto = new UserDTO();
            return View(dto);
        }

        public ActionResult Button()
        {
            UserDTO dto = new UserDTO();
            var name = "";
            if (Request.Files["image"] != null)
            {
                var file = Request.Files["image"];
                if (file.FileName != "")
                {
                    var ext = System.IO.Path.GetExtension(file.FileName);
                    name = Guid.NewGuid().ToString() + ext;
                    var rootPath = Server.MapPath("~/UploadedFiles");
                    var fileSavePath = System.IO.Path.Combine(rootPath, name);
                    file.SaveAs(fileSavePath);

                }
            }
            dto.ImageName = name;
            dto.UserID = (Int32)Session["UserID"];
            dto.Name = Request["Name"];
            dto.login = Request["login"];
            dto.password = Request["password"];
            String str = Request["gender"];
            if (Request["gender"] == "male")
                dto.gender = 'M';
            else
                dto.gender = 'F';
            dto.address = Request["address"];
            dto.age = Convert.ToInt32(Request["age"]);
            dto.NIC = Request["NIC"];
            dto.DOB = Convert.ToDateTime(Request["DOB"]);
            if (Request["isCricket"] != null)
                dto.isCricket = true;
            else
                dto.isCricket = false;
            if (Request["Hockey"] != null)
                dto.Hockey = true;
            else
                dto.Hockey = false;
            if (Request["Chess"] != null)
                dto.Chess = true;
            else
                dto.Chess = false;

            dto.CreatedOn = DateTime.Now;
            dto.Email = Request["Email"];
            int id = (Int32)Session["UserID"];
            if (Session["isAdmin"] != null)
            {
                return RedirectToAction("UserList", "Admin", null);
            }
            if (id > 0)
            {
                return View("Save", dto);
            }
            else
                return View("Start");
        }
        public ActionResult Edit()
        {
            String login = (String)Session["login"];
            UserDTO dto = UMS.BAL.UserBO.Edit(login);
            ViewBag.date = dto.DOB;
            return View("New", dto);
        }

        public ActionResult Home()
        {
            String login = (String)TempData["login"];
            UserDTO dto = UMS.BAL.UserBO.Home(login);
            return View("Save", dto);
        }
    }
}

UMS_2/UserManagementSystem/Views/User/New.cshtml
@model UMS.Entities.UserDTO
@{
    ViewBag.Title = "New";
    Layout = "~/Views/Shared/_MyUserLayout.cshtml";
}

<html>
<head>

    <style>
        body {
            background-color: white;
        }

        .div1 {
            background-color: white;
            padding: 10px;
            margin-left:400px;
            margin-top:80px;
            border: 50px black;
            border-radius: 5px;
            height: 480px;
            width: 500px;
            text-align: left;
        }
        .pos{
            border: none;
            color: white;
            padding: 15px 32px;
            background-color:rebeccapurple;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 280px;
            cursor: pointer;
            height:40px;
            width:80px;
        }
    </style>
    </head>
    <body>
        @{ 
           
            Session["image"] = null;
        }
        <h1 style="color:white;font-family:Verdana; background-color:black; text-align: center;">User Management System</h1>
        
        <div class="div1">
            
            <form action="~/User/Save" method="post" enctype="multipart/form-data">
                <table cellspacing="4" cellpadding="2">
                    @if (Model.ImageName != null)
                    {
                        <img src="~/UploadedFiles/@Model.ImageName" style="width:100px;height:100px; margin:7px 280px" />
                    }
                   @{
                       Session["image"] = Model.ImageName;
                    }
                   @{ 
                       Session["UserID"] = Model.UserID;
                   }
                    <tr>
                        <td> Name:</td>
                        <td><input id="name" name="Name" type="text" value="@Model.Name" required></td>
                    </tr>
                    <tr>
                        <td>Login:</td>
                        <td><input id="login" type="text" name="login" value="@Model.login" required></td>
                    </tr>
                    <tr>
                        <td> Password:</td>
                        <td><input id="password" type="password" name="password" value="@Model.password" required></td>
                    </tr>
                    <tr>
                        <td>Email: </td>
                        <td><input id="email" type="email" name="Email" value="@Model.Email" required></td>
                    </tr>
                    <tr>
                        <td> Gender:</td>
                        @{
                            var female = "";
                            var male = "";
                            if (Model.gender ==  'F')
                            {
                                female = "selected";
                            }
                            else if (Model.gender == 'M')
                            {
                                male = "selected";
                            }
                        }
                        <td><select name="gender" required>
                        <option value="">--Select--</option>
                        <option value='male' @male>Male</option>
                        <option value='female' @female>Female</option>
                        </select></td>
                    </tr>
                    <tr>
                        <td> Address:</td>
                        <td><input type="text" name="address" value="@Model.address" style="width:175px; height:40px;" required /></td>
                    </tr>
                    <tr>
                        <td> Upload:</td>
                        <td><input type="file"  id="image" name="image" value="~/uploadedFiles/@Model.ImageName"  /></td>
                    </tr>
                    <tr>
                        <td>  Age:</td>
                        <td><input type="number" name="age" value="@Model.age"></td>
                    </tr>
                    <tr>
                        <td>NIC:</td>
                        <td><input id="nic" type="text" name="NIC" value="@Model.NIC" required></td>
                    </tr>
                    <tr>
                        <td> DOB:</td>
                        <td><input type="date" name="DOB" value="@Model.DOB.ToString("yyy-MM-dd")" /></td>
                    </tr>
                    <tr>
                        <td> Sports:</td>
                         @{
                        var h = "";
                        var cr = "";
                        var ch ="";
                        if (Model.Chess == true) {
                            ch = "checked";
                        }
                        if (Model.isCricket == true) {
                            cr = "checked";
                        }
                        if (Model.Hockey == true) {
                            h = "checked";
                        }

                    }
                        <td><input type="checkbox" @cr name="isCricket" value="Cricket"> Cricket
                            <input type="checkbox" @h name="Hockey" value="Hockey"> Hockey
                           <input type="checkbox" @ch name="Chess" value="Chess">Chess</td>
                    </tr>
                    <tr>
                        <td><input type="submit" id="btn1" value="Save"></td>
                        <td><input type="submit" id="btn2" value="Cancel" onclick="@("window.location.href='" + @Url.Action("Button", "User") + "'")" ; /></td> 
                    </tr>
                </table>
            </form>
        </div>
    </body>
</html>

UMS_2/UserManagementSystem/Views/User/Save.cshtml
@model UMS.Entities.UserDTO
    @{
        if (Session["UserID"] != null) 
        {

            ViewBag.Title = "Save";
            Layout = "~/Views/Shared/_MyUserLayout.cshtml";


                <html>
                <head>
                    <style>
                        .div1 {
                            background-color: white;
                            padding: 10px;
                            margin: 150px 450px;
                            border: 50px black;
                            border-radius: 5px;
                            height: 400px;
                            width: 400px;
                            text-align: left;
                        }

                        .pos {
                            border: none;
                            color: white;
                            padding: 15px 32px;
                            background-color: rebeccapurple;
                            text-align: center;
                            text-decoration: none;
                            display: inline-block;
                            font-size: 16px;
                            margin: 4px 280px;
                            cursor: pointer;
                            height: 50px;
                            width: 100px;
                        }
                    </style>
                </head>
                @{
                    Session["login"] = null;
                }
                <body style="background-color:darkgray;">

                    <div class="div1">
                        <h1>Home Screen</h1>
                        Welcome @Model.login
                        @{
                            Session["login"] = Model.login;
                        }
                        <img src="~/UploadedFiles/@Model.ImageName" style="width:100px;height:100px; margin:4px 280px" /><br /><br />
                        <input type="submit" class="pos" name="edit" value="Edit" onclick="@("window.location.href='" + @Url.Action("Edit", "User") + "'");" />
                        <input type="submit" class="pos" name="logout" value="Logout" onclick="@("window.location.href='" + @Url.Action("Start", "User") + "'");" />
                    </div>
                </body>
            </html>


                            }
                            else
                            {
                                
                                <span>Please login First</span>
                            }
    }

UMS_2/UserManagementSystem/Views/User/start.cshtml
@{
    ViewBag.Title = "MainScreen";
    Layout = "~/Views/Shared/_MyUserLayout.cshtml";
}

<style>
    .button {
            background-color: rebeccapurple;
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            width: 200px;
            height: 50px;
        }
        .grid-container {
        display: grid;
        grid-template-columns: auto auto auto auto auto auto auto auto;
        grid-gap: 10px;
        background-color: white;
        padding: 1px;
        align-self:center;
    }

         div {
            background-color: white;
            padding: 10px;
            margin: 50px 200px;
            border: 50px black;
            border-radius: 5px;
            height: 400px;
            width: 400px;
            text-align: center;
        }
        .grid-container > div {
            background-color: darkgray;
            padding: 0px 0;
            margin-left:60px;           
            margin-top:30px;     
        }

    .item1 {
        grid-row: 1/4;
    }

</style>
@{ 
    Session["UserID"] = null;
    Session["isAdmin"] = null;
    Session["res"] = null;
}
    <div class="grid-container">
        <div class="item1" align="center">
            <h1>Main Screen</h1>
            <input type="submit" class="button" value="New User" id="newUser" onclick="@("window.location.href='" + @Url.Action("New", "User") + "'");"><br><br>
            <input type="submit" class="button" value="Existing User" id="existingUser" onclick="@("window.location.href='" + @Url.Action("Exist", "Existing") + "'");"><br><br>
            <input type="submit" class="button" value="Admin" id="admin" onclick="@("window.location.href='" + @Url.Action("login", "Admin") + "'");"><br><br>
            <input type="submit" class="button" value="Exit" id="exit" onclick="@("window.location.href='" + @Url.Action("", "") + "'");">

        </div>
        </div>